OM_Web/Models/Customer.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace OM_Web.Models
{
    public class Customer
    {
        [Key]
        public int Customer_ID { get; set; }

        [Required(ErrorMessage = "Company Name is mandatory")]
        [MaxLength(50, ErrorMessage = "Maximum Length of this field is 50 charachters")]
        [DisplayName ("Company")]
        public string Company { get; set; }

        [MaxLength(50, ErrorMessage = "Maximum Length of this field is 50 charachters")]
        [DisplayName("Last Name")]
        public string? Last_Name { get; set; }

        [MaxLength(50, ErrorMessage = "Maximum Length of this field is 50 charachters")]
        [DisplayName("First Name")]
        public string? First_Name { get; set; }

        [MaxLength(50, ErrorMessage = "Maximum Length of this field is 50 charachters")]
        [DisplayName("Email")]
        public string? E_Mail_Address { get; set; }

        [MaxLength(50, ErrorMessage = "Maximum Length of this field is 50 charachters")]
        [DisplayName("Job Titl")]
        public string? Job_Title { get; set; }

        [MaxLength(25, ErrorMessage = "Maximum Length of this field is 25 charachters")]
        [DisplayName("Business Phone")]
        public string? Business_Phone { get; set; }

        [MaxLength(25, ErrorMessage = "Maximum Length of this field is 25 charachters")]
        [DisplayName("Fax")]
        public string? Fax_Number { get; set; }

        public string? Address { get; set; }
        public string? Notes { get; set; }

    }
}

OM_Web/Models/ErrorViewModel.cs
namespace OM_Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OM_Web/Models/Order.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OM_Web.Models
{
    public class Order
    {
        [Key]
        [Required(ErrorMessage = "Order Number is mandatory")]
        [DisplayName("Order Number")]
        public int Order_No { get; set; }

        [Required(ErrorMessage = "Customer is mandatory")]
        [DisplayName("Company")]
        public int Customer_ID { get; set; }
        //[ForeignKey("Customer_ID")]
        //[ValidateNever]
        //public Customer Customer { get; set; }

        [DisplayName("Order Date")]
        [DisplayFormat(DataFormatString = "{dd/mm/yyyy}")]
        public DateTime? Order_Date { get; set; }

        [DisplayName("Shipping Fee")]
        public decimal? Shipping_Fee { get; set; }

        [DisplayName("Taxes")]
        public decimal? Taxes { get; set; }

        public string? Notes { get; set; }
    }
}

OM_Web/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using OM_Web.Data;
using OM_Web.Models;


namespace OM_Web.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CustomerController(ApplicationDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            List<Customer> objCustomerList = _db.Customers.ToList();
            return View(objCustomerList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Customer obj)
        {

            if (ModelState.IsValid)
            {
                _db.Customers.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Customer created successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var customerFromDb = _db.Customers.Find(id);
            if (customerFromDb == null)
            {
                return NotFound();
            }
            return View(customerFromDb);
        }

        [HttpPost]
        public IActionResult Update(Customer obj)
        {
            //--------The below code is for testing ModelState.AddModelError--------------------
            if (obj.Company != null && obj.Company.Contains("^"))
            {
                ModelState.AddModelError("Company", "Customer Name must not have '^' character");
            }
            if (obj.Company != null && obj.Company.ToLower()=="test")
            {
                ModelState.AddModelError("", "Hello Error!");
            }
            //-----------------------------------------------------------------------------------
            if (ModelState.IsValid)
            {
                _db.Customers.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Customer updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var customerFromDb = _db.Customers.Find(id);
            if (customerFromDb == null)
            {
                return NotFound();
            }
            return View(customerFromDb);
        }
        [HttpPost]
        public IActionResult Delete(Customer obj)
        {
            if (obj == null)
            {
                return NotFound();
            }

            _db.Customers.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Customer deleted successfully";
            return RedirectToAction("Index");
        }
    }

}

OM_Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using OM_Web.Models;

namespace OM_Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult FAQ()
        {
            return View();
        }

        public IActionResult AboutUs() 
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OM_Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using OM_Web.Data;
using OM_Web.Models;

namespace OM_Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _db;

        public OrderController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<Order> objOrderList = _db.Orders.ToList();
            return View(objOrderList);

            //return View();
        }
    }
}

OM_Web/Views/Customer/Create.cshtml
@model Customer

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary fw-bold">Create New Customer</h2>
            <hr />
        </div>
        <div asp-validation-summary="All" class="text-bg-danger"></div>
        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Company" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Company" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="Company" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Last_Name" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Last_Name" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="Last_Name" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="First_Name" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="First_Name" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="First_Name" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="E_Mail_Address" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="E_Mail_Address" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="E_Mail_Address" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Job_Title" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Job_Title" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="Job_Title" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Business_Phone" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Business_Phone" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="Business_Phone" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Fax_Number" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Fax_Number" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="Fax_Number" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Address" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Address" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        
        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Notes" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Notes" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="Notes" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">
                    <i class="bi bi-plus-circle"></i> Create
                </button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Customer" asp-action="Index" class="btn btn-outline-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

OM_Web/Views/Customer/Delete.cshtml
@model Customer

<form method="post">
    <input asp-for="Customer_ID" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary fw-bold">Edit Customer</h2>
            <hr />
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Company" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Company" class="form-control border p-2 shadow" disabled />
            </div>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Last_Name" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Last_Name" class="form-control border p-2 shadow" disabled />
            </div>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="First_Name" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="First_Name" class="form-control border p-2 shadow" disabled />
            </div>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="E_Mail_Address" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="E_Mail_Address" class="form-control border p-2 shadow" disabled />
            </div>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Job_Title" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Job_Title" class="form-control border p-2 shadow" disabled />
            </div>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Business_Phone" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Business_Phone" class="form-control border p-2 shadow" disabled />
            </div>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Fax_Number" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Fax_Number" class="form-control border p-2 shadow" disabled />
            </div>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Address" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Address" class="form-control border p-2 shadow" disabled />
            </div>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Notes" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Notes" class="form-control border p-2 shadow" disabled />
            </div>
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-danger form-control">
                    <i class="bi bi-trash3"></i> Delete
                </button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Customer" asp-action="Index" class="btn btn-outline-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

OM_Web/Views/Customer/Index.cshtml
@model List<OM_Web.Models.Customer>

@{
    ViewData["Title"] = "Customer List";
}

<div class="container mt-4">
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-primary fw-bold">@ViewData["Title"]</h2>
        </div>
        <div class="col-6 text-end">
            <a class="btn btn-primary fw-bold rounded-4" asp-controller="Customer" asp-action="Create">
                <i class="bi bi-plus-circle"></i> Create New Customer
            </a>
        </div>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Customer ID</th>
                <th>Company</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Fax</th>
                <th>Address</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Customer_ID</td>
                    <td>@item.Company</td>
                    <td>@item.E_Mail_Address</td>
                    <td>@item.Business_Phone</td>
                    <td>@item.Fax_Number</td>
                    <td>@item.Address</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Customer" asp-action="Update" asp-route-id="@item.Customer_ID" class="btn btn-primary mx-2 rounded-4">
                                <i class="bi bi-pencil"></i> Edit
                            </a>
                            <a asp-controller="Customer" asp-action="Delete" asp-route-id="@item.Customer_ID" class="btn btn-danger mx-2 rounded-4">
                                <i class="bi bi-trash3"></i> Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

OM_Web/Views/Customer/Update.cshtml
@model Customer

<form method="post">
    <input asp-for="Customer_ID" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary fw-bold">Edit Customer</h2>
            <hr />
        </div>
        <div asp-validation-summary="All" class="text-bg-danger"></div>
        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Company" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Company" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="Company" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Last_Name" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Last_Name" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="Last_Name" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="First_Name" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="First_Name" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="First_Name" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="E_Mail_Address" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="E_Mail_Address" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="E_Mail_Address" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Job_Title" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Job_Title" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="Job_Title" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Business_Phone" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Business_Phone" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="Business_Phone" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Fax_Number" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Fax_Number" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="Fax_Number" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Address" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Address" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>

        <div class="mb-2 row p-1">
            <div class="mb-3 col-2">
                <label asp-for="Notes" class="p-2 fw-bold"></label>
            </div>
            <div class="mb-3 col-9 p-0">
                <input asp-for="Notes" class="form-control border p-2 shadow" />
            </div>
            <span asp-validation-for="Notes" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">
                    <i class="bi bi-floppy"></i> Update
                </button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Customer" asp-action="Index" class="btn btn-outline-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

OM_Web/Views/Home/AboutUs.cshtml
<h3>About Us</h3>
<h6>Hellow Biz<h6>
        <p>Hellow Biz is a leading company in providing innovative solutions to businesses worldwide. Our mission is to empower organizations through cutting-edge technology and exceptional service.</p>

OM_Web/Views/Home/FAQ.cshtml
<h1>FAQ</h1>

OM_Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";   
}

<div class="text-center">
    <h1 class="display-4">Welcome All</h1>
    <h2>@ViewData["Greeting"]</h2>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OM_Web/Views/Order/Index.cshtml
@model List<OM_Web.Models.Order>

@{
    ViewData["Title"] = "Order List";
}

<div class="container mt-4">
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-primary fw-bold">@ViewData["Title"]</h2>
        </div>
        <div class="col-6 text-end">
            <a class="btn btn-primary rounded-4 fw-bold" asp-controller="Order" asp-action="Create">
                <i class="bi bi-plus-circle"></i> Create New Order
            </a>
        </div>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Order Number</th>
                <th>Company</th>
                <th>Date</th>
                <th>Shipping Fee</th>
                <th>Taxes</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Order_No</td>
                    <td>@item.Customer_ID</td>
                    <td>@item.Order_Date</td>
                    <td>@item.Shipping_Fee</td>
                    <td>@item.Taxes</td>
                    <td>@item. </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Order" asp-action="UpdateCustomer" asp-route-id="@item.Order_No" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil-square"></i> Edit
                            </a>
                            <a asp-controller="Order" asp-action="DeleteCustomer" asp-route-id="@item.Order_No" class="btn btn-danger mx-2">
                                <i class="bi bi-trash3"></i> Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

OM_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @* <title>@ViewData["Title"] - OM_Web</title> *@
    <title>Order Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OM_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Order Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="FAQ">FAQ</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">Aboutan Us</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - Order Management - <i class="bi bi-airplane"></i> <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OM_Web/Views/Shared/_Notification.cshtml
@* @if (TempData["success"]!=null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Success!</strong> @TempData["success"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
@if (TempData["error"]!=null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error!</strong> @TempData["error"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
 *@

@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}